/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.util.logging.Level;
import java.util.logging.Logger;

import java.sql.*;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Habib
 */
public class MainFrame extends javax.swing.JFrame {
        String url = "jdbc:mysql://localhost/new_schema";
        static String user; //="root";
        static String pass; //= "minecraft";
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(10);
        fillCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NameText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SalaryText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        HireText = new javax.swing.JTextField();
        HireBox = new javax.swing.JComboBox<>();
        DepBox = new javax.swing.JComboBox<>();
        SalaryBox = new javax.swing.JComboBox<>();
        AgeText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AgeBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        EmailText = new javax.swing.JTextField();
        FindBut = new javax.swing.JButton();
        DelBut = new javax.swing.JButton();
        AddBut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 30));

        NameText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(NameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 110, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Department:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Salary:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 30));

        SalaryText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SalaryText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaryTextActionPerformed(evt);
            }
        });
        jPanel1.add(SalaryText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 60, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Hire year:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, 30));

        HireText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(HireText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 60, 30));

        HireBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HireBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", "<", ">" }));
        jPanel1.add(HireBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 50, 30));

        DepBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DepBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(DepBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 120, 30));

        SalaryBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SalaryBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", "<", ">" }));
        jPanel1.add(SalaryBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 50, 30));

        AgeText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(AgeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 60, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Worker's Age:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, 30));

        AgeBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AgeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", "<", ">" }));
        jPanel1.add(AgeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 50, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Email:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 50, 30));

        EmailText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(EmailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 140, 30));

        FindBut.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        FindBut.setText("Find");
        FindBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindButActionPerformed(evt);
            }
        });
        jPanel1.add(FindBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 100, 40));

        DelBut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DelBut.setText("Delete");
        DelBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelButActionPerformed(evt);
            }
        });
        jPanel1.add(DelBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 100, 40));

        AddBut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AddBut.setText("Add");
        AddBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButActionPerformed(evt);
            }
        });
        jPanel1.add(AddBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 100, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 170));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Department", "Salary", "Worker's Age", "Hire year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 171, 710, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalaryTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaryTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalaryTextActionPerformed

    private void FindButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindButActionPerformed
    sqlCmd("SELECT *");
    }
    void sqlCmd(String arg){
        //String eqN=null,eqE=null,eqD=null;
        String word=" WHERE ";
        String sql = arg+" FROM workers"; //WHERE Name "+eqN+"'"+NameText.getText()+"'";
         if(arg=="INSERT")
       {sql = "INSERT INTO workers VALUES ('"+NameText.getText()+"','";
        sql+=EmailText.getText()+"','";
        sql+=DepBox.getSelectedItem()+"',";
        sql+=SalaryText.getText()+",";
        sql+=AgeText.getText()+",";
        sql+=HireText.getText()+")";}else{
         if(!NameText.getText().equals("")){
             sql+=word;word=" AND ";
             sql+="Name ='"+NameText.getText()+"'";}
       if(!EmailText.getText().equals("")){
           sql+=word;word=" AND ";
           sql+="Email ='"+EmailText.getText()+"'";}
       if(!SalaryText.getText().equals(""))
       {   sql+=word;word=" AND ";
           sql+="Salary"+SalaryBox.getSelectedItem()+SalaryText.getText();}
       if(!AgeText.getText().equals(""))
       {   sql+=word;word=" AND ";
           sql+="WorkerAge"+AgeBox.getSelectedItem()+AgeText.getText();}
       if(!HireText.getText().equals(""))
       {   sql+=word;word=" AND ";
           sql+="HireYear"+HireBox.getSelectedItem()+HireText.getText();}
       if(!DepBox.getSelectedItem().equals("All"))
       {   sql+=word;word=" AND ";
           sql+="Department ='"+DepBox.getSelectedItem().toString()+"'";}
         }
        Connection con;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(url,user,pass);
            PreparedStatement pst = con.prepareStatement(sql);
            if(arg!="SELECT *"){pst.executeUpdate();pst=con.prepareStatement("SELECT * FROM workers");}
                 ResultSet rs = pst.executeQuery();   
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)});
            }
            // TODO add your handling code here:
        } catch (Exception ex) {
            System.out.println("Error: "+ex.getMessage());
        }
    }//GEN-LAST:event_FindButActionPerformed

    private void AddButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButActionPerformed
        // TODO add your handling code here:
        sqlCmd("INSERT");
    }//GEN-LAST:event_AddButActionPerformed

    void fillCombo(){
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection(url,user,pass);
                PreparedStatement pst = con.prepareStatement("SELECT deport_type from deport_list");
                ResultSet rs = pst.executeQuery();
                Vector vector = new Vector();
                vector.addElement("All");
                while(rs.next()){
                   vector.addElement(rs.getString("deport_type"));
                }
                DepBox.setModel(new DefaultComboBoxModel(vector));
            } catch (Exception ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    
    
    }
    private void DelButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelButActionPerformed
        sqlCmd("DELETE");
        // TODO add your handling code here:
    }//GEN-LAST:event_DelButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        user=args[0]; pass=args[1];
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBut;
    private javax.swing.JComboBox<String> AgeBox;
    private javax.swing.JTextField AgeText;
    private javax.swing.JButton DelBut;
    private javax.swing.JComboBox<String> DepBox;
    private javax.swing.JTextField EmailText;
    private javax.swing.JButton FindBut;
    private javax.swing.JComboBox<String> HireBox;
    private javax.swing.JTextField HireText;
    private javax.swing.JTextField NameText;
    private javax.swing.JComboBox<String> SalaryBox;
    private javax.swing.JTextField SalaryText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
